dist: xenial
language: julia
julia: 1.0
notifications:
    email: true

matrix:
    include:
        - os: linux
        - os: osx

script:
    - while sleep 60; do echo "still alive"; done &
    - julia --color=yes -e '
          using Pkg;
          abstractalgebra_url
                  = "https://github.com/Nemocas/AbstractAlgebra.jl";
          Pkg.add(PackageSpec(url = abstractalgebra_url));
          nemo_url = "https://github.com/Nemocas/Nemo.jl";
          Pkg.add(PackageSpec(url = nemo_url));
          hecke_url = "https://github.com/thofma/Hecke.jl";
          Pkg.add(PackageSpec(url = hecke_url));
          singular_url = "https://github.com/oscar-system/Singular.jl";
          Pkg.add(PackageSpec(url = singular_url));
      '
    - kill %%
    - julia --color=yes -e '
          using Pkg;
          Pkg.add(PackageSpec(path = pwd()));
          Pkg.test("PrymGreen"; coverage = true);
      '

after_success:
    - julia --color=yes -e '
          using Pkg;
          import PrymGreen;
          cd(realpath(joinpath(dirname(pathof(PrymGreen)), "..")));
          # temporary workaround for
          # https://github.com/JuliaWeb/MbedTLS.jl/issues/193
          Pkg.add("MbedTLS@0.6.6");
          Pkg.add("Coverage");
          using Coverage;
          Coveralls.submit(Coveralls.process_folder());
          Codecov.submit(Codecov.process_folder());
      '
